name: CI Check

on:
    steps:
        name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

        name: Run simulated tests
        run: echo "Все автоматические проверки успешно пройдены!"
        name: TruffleHog OSS
        uses: trufflesecurity/trufflehog@main
        with:
          path: ./
          extra_args: --no-verification